;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


[bar/mainbar]
monitor = "eDP-1"
background = #20ffffff
foreground = #ffffff
font-0 = SF Pro Text:style=Medium:pixelsize=12;2
font-1 = Font Awesome 5 Free Solid:style=Regular:size=9;2
font-2 = Font Awesome 5 Brands:style=Regular:size=13;2
height = 24
line-size = 2
modules-left = host i3
modules-right = battery network datetime
padding = 3
module-margin = 1.5

[module/host]
type = custom/text
content = carmelo

[module/i3]
type = internal/i3
label-focused-underline = #FFFFFF
strip-wsnumber = true
label-mode-padding = 1
label-focused = %index%
label-unfocused = %index%
label-focused-padding = 1
label-unfocused-padding = 1
enable-scroll = false
reverse-scroll = false

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD

;  -- Iconos --
;format-charging = <ramp-capacity>
;format-discharging = <ramp-capacity>
;ramp-capacity-0 = ""
;ramp-capacity-1 = ""
;ramp-capacity-2 = ""
;ramp-capacity-3 = ""
;ramp-capacity-4 = ""

[module/network]
type = internal/network
interface = wlan0
label-disconnected = " Not connected"
label-connected = ""

[module/datetime]
type = internal/date
date = %a %b %d  %H:%M %p
